"""create jobs table

Revision ID: e46e46476a5c
Revises: 
Create Date: 2026-03-03 10:51:13.738063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e46e46476a5c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('jd_text', sa.Text(), nullable=True),
    sa.Column('job_url', sa.Text(), nullable=False),
    sa.Column('experience_required', sa.Float(), nullable=True),
    sa.Column('estimated_ctc', sa.Float(), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('selected', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_url')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    # ### end Alembic commands ###
